REQUEST_EXCEPTION = {
    "InvalidJSONError": "InvalidJSONError.sh",
    "HTTPError": "HTTPError.sh",
    "ConnectionError": "ConnectionError.sh",
    "ProxyError": "ProxyError.sh",
    "SSLError": "SSLError.sh",
    "Timeout": "Timeout.sh",
    "ConnectTimeout": "ConnectTimeout.sh",
    "ReadTimeout": "ReadTimeout.sh",
    "URLRequired": "URLRequired.sh",
    "TooManyRedirects": "TooManyRedirects.sh",
    "MissingSchema": "MissingSchema.sh",
    "InvalidSchema": "InvalidSchema.sh",
    "InvalidURL": "InvalidURL.sh",
    "InvalidHeader": "InvalidHeader.sh",
    "InvalidProxyURL": "InvalidProxyURL.sh",
    "ChunkedEncodingError": "ChunkedEncodingError.sh",
    "ContentDecodingError": "ContentDecodingError.sh",
    "StreamConsumedError": "StreamConsumedError.sh",
    "RetryError": "RetryError.sh",
    "UnrewindableBodyError": "UnrewindableBodyError.sh",
}

NETWORK_EXCEPTION = {
    203: "SuccessCodes\\203_Non-AuthoritativeInformation.sh",
    204: "SuccessCodes\\204_NoContent.sh",
    205: "SuccessCodes\\205_ResetContent.sh",
    206: "SuccessCodes\\206_PartialContent.sh",
    300: "RedirectionCodes\\300_MultipleChoices.sh",
    301: "RedirectionCodes\\301_MovedPermanently.sh",
    302: "RedirectionCodes\\302_MovedTemporarily.sh",
    303: "RedirectionCodes\\303_SeeOther.sh",
    304: "RedirectionCodes\\304_NotModified.sh",
    305: "RedirectionCodes\\305_UseProxy.sh",
    306: "RedirectionCodes\\306_NotUsed.sh",
    307: "RedirectionCodes\\307_TemporaryRedirect.sh",
    400: "FailureCodes\\400_BadRequest.sh",
    401: "FailureCodes\\401_Unauthorized.sh",
    402: "FailureCodes\\402_PaymentRequired.sh",
    403: "FailureCodes\\403_Forbidden.sh",
    404: "FailureCodes\\404_NotFound.sh",
    405: "FailureCodes\\405_MethodNotAllowed.sh",
    406: "FailureCodes\\406_NotAcceptable.sh",
    407: "FailureCodes\\407_ProxyAuthenticationRequired.sh",
    408: "FailureCodes\\408_RequestTime-out.sh",
    409: "FailureCodes\\409_Conflict.sh",
    410: "FailureCodes\\410_Gone.sh",
    411: "FailureCodes\\411_LengthRequired.sh",
    412: "FailureCodes\\412_PreconditionFailed.sh",
    413: "FailureCodes\\413_RequestEntityTooLarge.sh",
    414: "FailureCodes\\414_Request-URITooLong.sh",
    415: "FailureCodes\\415_UnsupportedMediaType.sh",
    416: "FailureCodes\\416_RequestedRangeNotSatisfiable.sh",
    417: "FailureCodes\\417_ExpectationFailed.sh",
    500: "ServerErrorCodes\\500_InternalServerError.sh",
    501: "ServerErrorCodes\\501_NotImplemented.sh",
    502: "ServerErrorCodes\\502_BadGateway.sh",
    503: "ServerErrorCodes\\503_ServiceUnavailable.sh",
    504: "ServerErrorCodes\\504_GatewayTime-out.sh",
    505: "ServerErrorCodes\\505_HTTPVersionnotsupported.sh",
}

SYSTEM_EXCEPTION = {}
